### PR TITLE
feat: add onSubmitTransform

### PR DESCRIPTION
**Pull request by Anon-136**
## Proposed Changes
* Transform values on submit, as requested at #60.
* Since input `type='number'` is usually a bad ux, I prefer `type='text'` with normal string and transform it to number later.
* So I propose `onSubmitTransform` that runs before form submission and after input validations.
* It can take in either **normal function**, **async function**, or **zod transform** as an input.
* It also set errors if it fails to parse.

### Type of change
* New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Review by crutchcorn — APPROVED** [review]
This is awesome, thank you for the contribution!

Assuming tests pass, we can merge :D

**Comment by crutchcorn** [comment]
Actually, something I had a thought about before we merge - can we add reference docs for this feature? :)

**Comment by Anon-136** [comment]
Trying my best here
I don't know if this is enough.
I'm not good at docs writing
Feel free to edit

**Review by crutchcorn — APPROVED** [review]
This is amazing, thank you!

**Comment by crutchcorn** [comment]
@allcontributors please add @Anon-136 for docs, tests, code

**Pull request merged**
